---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: table1rkansiblerg
        location: westus
      register: rg
    - debug:
        var: rg
 
